// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahnMj0UVAjVt65veLX5_6lonN5VZHTkg',
    appId: '1:600227666927:web:bb0ed6b3ebb327d322f41a',
    messagingSenderId: '600227666927',
    projectId: 'technoart-monitor',
    authDomain: 'technoart-monitor.firebaseapp.com',
    storageBucket: 'technoart-monitor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtN75uU7UIxUiP3gKVS-PRLGi4gOYZJ68',
    appId: '1:600227666927:android:6799ee044a48fa2022f41a',
    messagingSenderId: '600227666927',
    projectId: 'technoart-monitor',
    storageBucket: 'technoart-monitor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb8wn7IGtTx8CX3p63RfP_fA7uvfBXc5Y',
    appId: '1:600227666927:ios:613aba1a4b163ef622f41a',
    messagingSenderId: '600227666927',
    projectId: 'technoart-monitor',
    storageBucket: 'technoart-monitor.appspot.com',
    iosClientId: '600227666927-b8pglgpmiie6knp9sfe2i5bk9ogsq4ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.technoartMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb8wn7IGtTx8CX3p63RfP_fA7uvfBXc5Y',
    appId: '1:600227666927:ios:613aba1a4b163ef622f41a',
    messagingSenderId: '600227666927',
    projectId: 'technoart-monitor',
    storageBucket: 'technoart-monitor.appspot.com',
    iosClientId: '600227666927-b8pglgpmiie6knp9sfe2i5bk9ogsq4ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.technoartMonitoring',
  );
}
